version: "3"

services:
  # Applications
  entrypoint:
    image: pipeline-entrypoint:0.0.1
    working_dir: /app
    volumes:
        - ./apps/entrypoint:/app
    ports:
      - 8080:8080
    command: make run

  enrichment:
    image: pipeline-enrichment:0.0.1
    working_dir: /app
    volumes:
        - ./apps/enrichment:/app
    ports:
      - 8081:8080
    command: make run

  response-builder:
    image: pipeline-response-builder:0.0.1
    working_dir: /app
    volumes:
        - ./apps/response-builder:/app
    ports:
      - 8082:8080
    command: make run

  # Datastores
  # Monitoring
