version: "3"

services:
  # Applications
  apigateway:
    image: pipeline-apigateway:0.0.1
    working_dir: /app
    environment:
      GOPROXY: direct
    volumes:
        - ./apps/apigateway:/app
    ports:
      - 8080:8080
      - 8880:8888
    command: make run

  # Monitoring
  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    ports:
      - 16686:16686
