version: "3"

services:
  # Applications
  apigateway:
    image: pipeline-apigateway:0.0.1
    working_dir: /app
    environment:
      GOPROXY: direct
      PUBSUB_EMULATOR_HOST: pubsub:8432
      PUBSUB_PROJECT_ID: my_project
      PUBSUB_REQUEST_TOPIC: foobar_req_topic
      PUBSUB_RESPONSE_SUBSCRIPTION: foobar_resp_sub
    volumes:
        - ./apps/apigateway:/app
    ports:
      - 8080:8080
      - 8880:8888
    command: make run

  foobar:
    image: pipeline-foobar:0.0.1
    working_dir: /app
    environment:
      REQUEST_SUBSCRIPTION: foobar_req_sub
      RESPONSE_TOPIC: foobar_resp_topic
    volumes:
        - ./apps/foobar:/app
    ports:
      - 8081:8080
    command: make run

  # GCP PubSub emulator
  pubsub:
    image: messagebird/gcloud-pubsub-emulator
    environment:
      PUBSUB_PROJECT: my_project,foobar_req_topic:foobar_req_sub,foobar_resp_topic:foobar_resp_sub

  # Monitoring
  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    ports:
      - 16686:16686
