version: 2.1
jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build-and-publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: mjmcconnell/go-gke-pipeline-proxy
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: echo $DOCKER_USERNAME
      - run:
          name: Log into docker hub
          command: echo $CI_DOCKER_ACCESS_KEY | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest apps/proxy
      - run:
          name: Publish Docker Image to Docker Hub
          command: docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - test
      - build-and-publish:
          requires:
            - test
          filters:
            branches:
              only: master
