version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build-and-publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: mjmcconnell/go-gke-pipeline-proxy
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: echo $DOCKER_USERNAME
      - run:
          name: Log into docker hub
          command: echo $CI_DOCKER_ACCESS_KEY | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:${CIRCLE_TAG} --file docker/Dockerfile.proxy .
      - run:
          name: Publish Docker Image to Docker Hub
          command: docker push $IMAGE_NAME:${CIRCLE_TAG}
workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - build-and-publish:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
