apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
spec:
  sessionAffinity:
    affinityType: "CLIENT_IP"
