FROM golang:1.15.3-alpine3.12 as builder

RUN apk add --no-cache \
    gcc \
    git \
    make

WORKDIR /proxy

COPY apps/proxy/cmd/ cmd/
COPY apps/proxy/pkg/ pkg/
COPY apps/proxy/go.mod go.mod
COPY apps/proxy/go.sum go.sum
COPY apps/proxy/Makefile Makefile

RUN make go.build

FROM alpine:3.12

COPY --from=builder /proxy/build/bin/ /usr/local/bin/

ENTRYPOINT ["proxy"]
